/**
 * exportWord.ts — LexAnalyze Word document export utility.
 *
 * DISCLAIMER: Generated reports are for informational purposes only.
 * They do NOT constitute legal advice. Always consult a qualified legal professional.
 */
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from "docx";
import type { AnalysisResponse } from "../types";

function navyHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, bold: true, color: "0F2744", size: 24 })],
    spacing: { before: 240, after: 80 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "C9A84C", space: 4 } },
  });
}

function bodyPara(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: 20, color: "2D3748" })],
    spacing: { after: 100 },
  });
}

function labelLine(label: string, value: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 19, color: "0F2744" }),
      new TextRun({ text: value || "Not found", size: 19, color: "4A5568" }),
    ],
    spacing: { after: 60 },
  });
}

function footerPara(): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({
        text: "Generated by LexAnalyze  |  Not legal advice",
        size: 16, color: "8A9AB0", italics: true,
      }),
    ],
    spacing: { before: 400 },
    border: { top: { style: BorderStyle.SINGLE, size: 4, color: "C9A84C", space: 8 } },
  });
}

export async function exportToWord(
  result: AnalysisResponse,
  filename: string,
  language = "en",
  languageName = "English",
): Promise<void> {
  const ov = result.case_overview;
  const cd = result.case_details;

  const children: Paragraph[] = [
    // Title
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: "LexAnalyze — Case Analysis Report", bold: true, color: "0F2744", size: 32 })],
      spacing: { after: 160 },
    }),

    // File metadata
    labelLine("File",        filename),
    labelLine("Pages",       String(result.page_count)),
    labelLine("OCR Used",    result.used_ocr ? "Yes" : "No"),
    labelLine("Document ID", result.document_id),
    labelLine("Exported",    new Date().toLocaleString()),

    // Translation note
    ...(language !== "en" ? [
      new Paragraph({
        children: [
          new TextRun({
            text: `Note: This report has been translated to ${languageName} using AI. Original document was in English.`,
            size: 16, color: "8A9AB0", italics: true,
          }),
        ],
        spacing: { after: 60 },
      }),
    ] : []),

    new Paragraph({ children: [], spacing: { after: 160 } }),

    // ── Case Overview ──
    navyHeading("Case Overview"),
    labelLine("Filed By",    ov.complainant),
    labelLine("Against",     ov.accused),
    labelLine("Court",       ov.court),
    labelLine("Case Number", ov.case_number),
    labelLine("Judges",      ov.judges.join(", ")),
    labelLine("Lawyers",     ov.lawyers.join(", ")),

    new Paragraph({ children: [], spacing: { after: 160 } }),

    // ── Case Details ──
    navyHeading("Case Details"),

    new Paragraph({
      children: [new TextRun({ text: "What Happened", bold: true, size: 20, color: "0F2744" })],
      spacing: { after: 40 },
    }),
    bodyPara(cd.what_happened || "Not available"),

    new Paragraph({
      children: [new TextRun({ text: "Crime / Legal Issue", bold: true, size: 20, color: "0F2744" })],
      spacing: { before: 120, after: 40 },
    }),
    bodyPara(cd.crime_or_issue || "Not identified"),

    ...(cd.sections_involved.length > 0 ? [
      new Paragraph({
        children: [new TextRun({ text: "Sections Involved", bold: true, size: 20, color: "0F2744" })],
        spacing: { before: 120, after: 40 },
      }),
      bodyPara(cd.sections_involved.join("  |  ")),
    ] : []),

    ...(cd.judgment ? [
      new Paragraph({
        children: [new TextRun({ text: "Judgment", bold: true, size: 20, color: "0F2744" })],
        spacing: { before: 120, after: 40 },
      }),
      new Paragraph({
        children: [new TextRun({ text: cd.judgment, size: 20, color: "2D3748" })],
        spacing: { after: 100 },
        shading: { type: ShadingType.SOLID, color: "F4F6F9", fill: "F4F6F9" },
      }),
    ] : []),

    labelLine("Judgment Date",    cd.judgment_date),
    labelLine("Penalty / Relief", cd.penalty_or_relief),

    new Paragraph({ children: [], spacing: { after: 160 } }),

    // ── Similar Cases ──
    ...(result.similar_cases.length > 0 ? [
      navyHeading("Similar Cases"),
      ...result.similar_cases.flatMap((sc) => {
        const pct = Math.round(sc.similarity_score * 100);
        return [
          new Paragraph({
            children: [
              new TextRun({ text: sc.title, bold: true, size: 20, color: "0F2744" }),
              new TextRun({ text: `  (${pct}% similar)`, size: 18, color: "8A9AB0" }),
            ],
            spacing: { before: 120, after: 40 },
          }),
          ...(sc.issue ? [bodyPara(`Issue: ${sc.issue}`)] : []),
          ...(sc.judgment_summary ? [bodyPara(`Judgment: ${sc.judgment_summary}`)] : []),
          new Paragraph({ children: [], spacing: { after: 60 } }),
        ];
      }),
    ] : []),

    footerPara(),
  ];

  const doc = new Document({
    sections: [{ children }],
    creator: "LexAnalyze",
    title: `Case Analysis Report — ${filename}`,
    description: "Generated by LexAnalyze. Not legal advice.",
  });

  const blob = await Packer.toBlob(doc);
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `${filename.replace(/\.pdf$/i, "")}_LexAnalyze.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
